"""Dashboard endpoints feeding usage aggregates to the frontend."""

import json
from pathlib import Path
from typing import Any

from fastapi import APIRouter, Depends, Request

from app.core.dependencies import get_session_id
from app.services.usage_store import UsageStore

router = APIRouter(prefix="/api/v1/dashboard", tags=["dashboard"])

_SCORECARD_PATH = (
    Path(__file__).resolve().parents[4] / "evaluation" / "results" / "ragas_scorecard.json"
)


def _get_usage_store(request: Request) -> UsageStore:
    store: UsageStore = request.app.state.usage_store
    return store


@router.get("/summary")
def summary(
    request: Request, session_id: str | None = Depends(get_session_id)
) -> dict[str, Any]:
    """Return aggregate usage metrics (total cost, latency, blocked, reviews).

    Scoped to the caller's `X-Session-Id` when present, so a fresh browser
    session starts at zero instead of showing the service's lifetime totals;
    omit the header (e.g. from an ops script) to get the full aggregate.
    """
    return _get_usage_store(request).summary(session_id=session_id)


@router.get("/recent")
def recent(
    request: Request, limit: int = 20, session_id: str | None = Depends(get_session_id)
) -> list[dict[str, Any]]:
    """Return the most recent requests' usage metadata, scoped like `/summary`."""
    return _get_usage_store(request).recent(limit=limit, session_id=session_id)


# Success thresholds from the project's "Objetivo del proyecto" (PLAN.md / README.md).
_QUALITY_THRESHOLDS = {
    "faithfulness": 0.85,
    "answer_relevancy": 0.85,
    "context_precision": 0.75,
    "context_recall": 0.75,
}


@router.get("/quality")
def quality() -> dict[str, Any]:
    """Return the latest EDD scorecard (RAGAS-style metrics) with pass/fail flags.

    Surfaces the same numbers published in the README, generated by
    `evaluation/run_ragas.py`, so the operational dashboard is never
    disconnected from the project's quality thresholds — cost and latency
    without a quality signal is an incomplete picture of a RAG system.
    """
    if not _SCORECARD_PATH.exists():
        return {"available": False}

    scorecard = json.loads(_SCORECARD_PATH.read_text(encoding="utf-8"))
    metrics = {
        name: {
            "score": scorecard.get(name),
            "threshold": threshold,
            "passing": (scorecard.get(name) or 0) >= threshold,
        }
        for name, threshold in _QUALITY_THRESHOLDS.items()
    }
    return {
        "available": True,
        "generated_at": scorecard.get("generated_at"),
        "metrics": metrics,
    }
